// AUTO-GENERATED by scripts/gen-portal-abi.py — do not edit by hand.
// Source: contracts-reference/IPortal.sol
//   from https://github.com/flap-sh/FlapVaultExample (src/flap/IPortal.sol)
//   commit 5949cc7eb99bcb5ac5f679cc710ae456e627f12a 2026-09-23T17:00:27+08:00
// Enums are encoded as uint8, exactly as the Solidity ABI encoder does.

export const portalAbi = [
  {
    "type": "function",
    "name": "newTokenV6",
    "stateMutability": "payable",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct NewTokenV6Params",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "meta",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "dexThresh",
            "type": "uint8",
            "internalType": "enum DexThreshType"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "migratorType",
            "type": "uint8",
            "internalType": "enum MigratorType"
          },
          {
            "name": "quoteToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "quoteAmt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "beneficiary",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "permitData",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "extensionID",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "extensionData",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "dexId",
            "type": "uint8",
            "internalType": "enum DEXId"
          },
          {
            "name": "lpFeeProfile",
            "type": "uint8",
            "internalType": "enum V3LPFeeProfile"
          },
          {
            "name": "buyTaxRate",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "sellTaxRate",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "taxDuration",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "antiFarmerDuration",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "mktBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "deflationBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "dividendBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "lpBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minimumShareBalance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dividendToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "commissionReceiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenVersion",
            "type": "uint8",
            "internalType": "enum TokenVersion"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "quoteExactInput",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct QuoteExactInputParams",
        "components": [
          {
            "name": "inputToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "outputToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "inputAmount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "outputAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "swapExactInput",
    "stateMutability": "payable",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct ExactInputParams",
        "components": [
          {
            "name": "inputToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "outputToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "inputAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minOutputAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "permitData",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "outputAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "getTokenV8Safe",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "state",
        "type": "tuple",
        "internalType": "struct TokenStateV8Safe",
        "components": [
          {
            "name": "status",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "reserve",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "circulatingSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tokenVersion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "r",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "h",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "k",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dexSupplyThresh",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "quoteTokenAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "nativeToQuoteSwapEnabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "extensionID",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "buyTaxRate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sellTaxRate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pool",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "progress",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lpFeeProfile",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "dexId",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ]
  },
  {
    "type": "function",
    "name": "getTokenV6",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "state",
        "type": "tuple",
        "internalType": "struct TokenStateV6",
        "components": [
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum TokenStatus"
          },
          {
            "name": "reserve",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "circulatingSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tokenVersion",
            "type": "uint8",
            "internalType": "enum TokenVersion"
          },
          {
            "name": "r",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "h",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "k",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dexSupplyThresh",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "quoteTokenAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "nativeToQuoteSwapEnabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "extensionID",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "taxRate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pool",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "progress",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ]
  },
  {
    "type": "function",
    "name": "getQuoteTokenConfiguration",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "quoteToken",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct QuoteTokenConfiguration",
        "components": [
          {
            "name": "enabled",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "defaultCurve",
            "type": "uint8",
            "internalType": "enum CurveType"
          },
          {
            "name": "alternativeCurve",
            "type": "uint8",
            "internalType": "enum CurveType"
          },
          {
            "name": "nativeToQuoteSwapType",
            "type": "uint8",
            "internalType": "enum NativeToQuoteSwapType"
          },
          {
            "name": "dexId",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ]
  },
  {
    "type": "function",
    "name": "getFeeRate",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "buyFeeRate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sellFeeRate",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "version",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "function",
    "name": "nonce",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "previewBuy",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "eth",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "previewSell",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "eth",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "event",
    "name": "TokenCreated",
    "anonymous": false,
    "inputs": [
      {
        "name": "ts",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "creator",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "nonce",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string",
        "indexed": false
      },
      {
        "name": "symbol",
        "type": "string",
        "internalType": "string",
        "indexed": false
      },
      {
        "name": "meta",
        "type": "string",
        "internalType": "string",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "TokenBought",
    "anonymous": false,
    "inputs": [
      {
        "name": "ts",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "buyer",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "eth",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "postPrice",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "TokenSold",
    "anonymous": false,
    "inputs": [
      {
        "name": "ts",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "seller",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "eth",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "postPrice",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "LaunchedToDEX",
    "anonymous": false,
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "pool",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "eth",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "FlapTokenProgressChanged",
    "anonymous": false,
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "newProgress",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "TokenQuoteSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "quoteToken",
        "type": "address",
        "internalType": "address",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "FlapTokenAsymmetricTaxSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "buyTax",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      },
      {
        "name": "sellTax",
        "type": "uint256",
        "internalType": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "QuoteTokenConfigurationSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "quoteToken",
        "type": "address",
        "internalType": "address",
        "indexed": false
      },
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct QuoteTokenConfiguration",
        "components": [
          {
            "name": "enabled",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "defaultCurve",
            "type": "uint8",
            "internalType": "enum CurveType"
          },
          {
            "name": "alternativeCurve",
            "type": "uint8",
            "internalType": "enum CurveType"
          },
          {
            "name": "nativeToQuoteSwapType",
            "type": "uint8",
            "internalType": "enum NativeToQuoteSwapType"
          },
          {
            "name": "dexId",
            "type": "uint8",
            "internalType": "uint8"
          }
        ],
        "indexed": false
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidCurveType",
    "inputs": [
      {
        "name": "curveType",
        "type": "uint8",
        "internalType": "enum CurveType"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidDexThresholdType",
    "inputs": [
      {
        "name": "threshold",
        "type": "uint8",
        "internalType": "enum DexThreshType"
      }
    ]
  },
  {
    "type": "error",
    "name": "DEXCannotBeBothPancakeAndAlgebra1_9",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PortalLensCannotBeZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MultiDexRouterCannotBeZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TokenNotFound",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "AmountTooSmall",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SlippageTooHigh",
    "inputs": [
      {
        "name": "actualAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SameToken",
    "inputs": [
      {
        "name": "tokenA",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenKilled",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenNotTradable",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenInDuel",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenNotKilled",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenAlreadyDEXed",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenAlreadyStaged",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenNotStaged",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenNotDEXed",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoConversionPath",
    "inputs": [
      {
        "name": "srcToken",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "dstToken",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "RoundNotFound",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidRoundID",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "LastRoundNotResolved",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidTokenForBattle",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSigner",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SeqNotFound",
    "inputs": [
      {
        "name": "seq",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotImplemented",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TokenAlreadyInGame",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "CallReverted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PermissionlessCreateDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TradeDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProtocolDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidGameSupplyThreshold",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidDEXSupplyThreshold",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MismatchedAddressInProof",
    "inputs": [
      {
        "name": "expected",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "actual",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoQuotaForCreator",
    "inputs": [
      {
        "name": "created",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidPiggybackLength",
    "inputs": [
      {
        "name": "expected",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "actual",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "FeatureDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OnlySaleForge",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuoteTokenNotAllowed",
    "inputs": [
      {
        "name": "quoteToken",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NativeToQuoteSwapNotSupported",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NativeToQuoteSwapFeeTierNotSupported",
    "inputs": [
      {
        "name": "NativeToQuoteSwapType",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "DirtyBits",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PriceAMustLTPriceB",
    "inputs": [
      {
        "name": "sqrtPriceA",
        "type": "uint160",
        "internalType": "uint160"
      },
      {
        "name": "sqrtPriceB",
        "type": "uint160",
        "internalType": "uint160"
      }
    ]
  },
  {
    "type": "error",
    "name": "ActualAmountMustLTEAmount",
    "inputs": [
      {
        "name": "actualAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amount1",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotUniswapV3Pool",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UniswapV2PoolNotZero",
    "inputs": [
      {
        "name": "pool",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "liquidity",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RequiredTokenMustLTE",
    "inputs": [
      {
        "name": "requiredToken",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "reserveToken",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UniswapV3Slot0Failed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NonPositionNFTReceived",
    "inputs": [
      {
        "name": "collection",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidDexThreshold",
    "inputs": [
      {
        "name": "threshold",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidPoolAddress",
    "inputs": [
      {
        "name": "pool",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "expected",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidLocks",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StakingDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotRoller",
    "inputs": []
  },
  {
    "type": "error",
    "name": "cannotCheckInUntil",
    "inputs": [
      {
        "name": "next",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "MetaAlreadyUsedByOtherToken",
    "inputs": [
      {
        "name": "meta",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "InsufficientCreationFee",
    "inputs": [
      {
        "name": "required",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "provided",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InsufficientFee",
    "inputs": [
      {
        "name": "required",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "provided",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "VanityAddressRequirementNotMet",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenNotInDEXStatus",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "CallerNotBeneficiary",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "expected",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoLocksAvailable",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InsufficientEth",
    "inputs": [
      {
        "name": "provided",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "required",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidTaxBps",
    "inputs": [
      {
        "name": "tax",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TransferFromFailed",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidMigratorType",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuoteTokenNotNativeButNotUsingTradeV2",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientValueForTaxTokenCreation",
    "inputs": [
      {
        "name": "expected",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "provided",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotGuardian",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedExtensionVersion",
    "inputs": [
      {
        "name": "version",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenWithExtensionNotSupported",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidParamsForToshiMart",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidParamsForXLayer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidQuoteTokenConfiguration",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ErrShouldUsePortalTradeV2",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoSupportedDEX",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidFeeTierForDEX",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidTaxDistribution",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TaxDurationTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TaxDurationTooShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AntiFarmerDurationTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AntiFarmerDurationTooShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MinimumShareBalanceTooLow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DividendParametersRequired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RateLimitExceeded",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "lastCreationTime",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SpammerBlocked",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SaltLockFeeMismatch",
    "inputs": [
      {
        "name": "required",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "provided",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SaltAlreadyLockedByAnotherUser",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "existingLocker",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SaltAlreadyLockedBySelf",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "FlapSaltLockedByAnotherUser",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "locker",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SaltLockTokenVersionMismatch",
    "inputs": [
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "locked",
        "type": "uint8",
        "internalType": "enum TokenVersion"
      },
      {
        "name": "provided",
        "type": "uint8",
        "internalType": "enum TokenVersion"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedTokenVersion",
    "inputs": [
      {
        "name": "provided",
        "type": "uint8",
        "internalType": "enum TokenVersion"
      }
    ]
  }
] as const;
