#!/usr/bin/env python3
"""
Generate lib/contracts/portal-abi.ts from the official Portal interface
(contracts-reference/IPortal.sol, copied from github.com/flap-sh/FlapVaultExample).

Only the functions/events/errors Coded Markets uses are emitted, but every
struct is expanded field-by-field straight from the Solidity source, so the
ABI cannot drift from the interface by hand-editing. Enums become uint8.

Usage:  python3 scripts/gen-portal-abi.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = (ROOT / "contracts-reference" / "IPortal.sol").read_text()
COMMIT = (ROOT / "contracts-reference" / "SOURCE_COMMIT.txt").read_text().strip()

# strip comments
code = re.sub(r"/\*.*?\*/", "", SRC, flags=re.S)
code = re.sub(r"//[^\n]*", "", code)

enums = set(re.findall(r"\benum\s+(\w+)\s*\{", code))
structs = {}
for name, body in re.findall(r"\bstruct\s+(\w+)\s*\{(.*?)\}", code, flags=re.S):
    fields = []
    for decl in body.split(";"):
        decl = " ".join(decl.split())
        if not decl:
            continue
        typ, fname = decl.rsplit(" ", 1)
        fields.append((typ, fname))
    structs[name] = fields


def abi_param(typ, name):
    typ = typ.replace("calldata", "").replace("memory", "").replace("indexed", "").strip()
    typ = typ.split(".")[-1]  # IPortalTypes.X -> X
    arr = ""
    m = re.match(r"^(\w+)((\[\d*\])*)$", typ)
    if not m:
        raise SystemExit(f"cannot parse type {typ!r}")
    base, arr = m.group(1), m.group(2) or ""
    if base in structs:
        return {"name": name, "type": "tuple" + arr, "internalType": f"struct {base}{arr}",
                "components": [abi_param(t, n) for t, n in structs[base]]}
    if base in enums:
        return {"name": name, "type": "uint8" + arr, "internalType": f"enum {base}{arr}"}
    if base == "uint":
        base = "uint256"
    return {"name": name, "type": base + arr, "internalType": base + arr}


def split_params(s):
    s = s.strip()
    if not s:
        return []
    out = []
    for p in s.split(","):
        toks = " ".join(p.split()).split(" ")
        toks = [t for t in toks if t not in ("calldata", "memory", "storage", "indexed")]
        if len(toks) == 1:
            out.append((toks[0], ""))
        else:
            out.append((toks[0], toks[-1]))
    return out


def find_function(name):
    m = re.search(r"function\s+" + name + r"\s*\((.*?)\)\s*([^;{]*?)(returns\s*\((.*?)\))?\s*;", code, flags=re.S)
    if not m:
        raise SystemExit(f"function {name} not found")
    params, modifiers, _, returns = m.group(1), m.group(2), m.group(3), m.group(4)
    mods = modifiers.split()
    mut = "view" if "view" in mods else "pure" if "pure" in mods else "payable" if "payable" in mods else "nonpayable"
    return {
        "type": "function", "name": name, "stateMutability": mut,
        "inputs": [abi_param(t, n) for t, n in split_params(params)],
        "outputs": [abi_param(t, n) for t, n in split_params(returns or "")],
    }


def find_event(name):
    m = re.search(r"event\s+" + name + r"\s*\((.*?)\)\s*;", code, flags=re.S)
    if not m:
        raise SystemExit(f"event {name} not found")
    inputs = []
    for p in m.group(1).split(","):
        toks = " ".join(p.split()).split(" ")
        indexed = "indexed" in toks
        toks = [t for t in toks if t != "indexed"]
        prm = abi_param(toks[0], toks[-1])
        prm["indexed"] = indexed
        inputs.append(prm)
    return {"type": "event", "name": name, "anonymous": False, "inputs": inputs}


FUNCTIONS = [
    "newTokenV6", "quoteExactInput", "swapExactInput", "getTokenV8Safe",
    "getTokenV6", "getQuoteTokenConfiguration", "getFeeRate", "version", "nonce", "previewBuy", "previewSell",
]
EVENTS = [
    "TokenCreated", "TokenBought", "TokenSold", "LaunchedToDEX", "FlapTokenProgressChanged",
    "TokenQuoteSet", "FlapTokenAsymmetricTaxSet", "QuoteTokenConfigurationSet",
]

abi = [find_function(f) for f in FUNCTIONS] + [find_event(e) for e in EVENTS]

# every custom error in the interface, for revert decoding
for ename, params in re.findall(r"\berror\s+(\w+)\s*\((.*?)\)\s*;", code, flags=re.S):
    abi.append({"type": "error", "name": ename,
                "inputs": [abi_param(t, n) for t, n in split_params(params)]})

out = ROOT / "lib" / "contracts" / "portal-abi.ts"
header = f"""// AUTO-GENERATED by scripts/gen-portal-abi.py — do not edit by hand.
// Source: contracts-reference/IPortal.sol
//   from https://github.com/flap-sh/FlapVaultExample (src/flap/IPortal.sol)
//   commit {COMMIT}
// Enums are encoded as uint8, exactly as the Solidity ABI encoder does.

"""
out.write_text(header + "export const portalAbi = " + json.dumps(abi, indent=2) + " as const;\n")
print(f"wrote {out.relative_to(ROOT)}: {len(abi)} entries", file=sys.stderr)
